= Setup Oracle Database
:linkattrs:
:project-owner: aalmiray
:project-name:  setup-oracledb
:project-tag:   v1

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://img.shields.io/github/v/release/{project-owner}/{project-name}["GitHub release", link="https://github.com/jreleaser/release-action/releases"]
image:https://img.shields.io/twitter/follow/{project-owner}?style=social["Twitter Follow", link="https://twitter.com/aalmiray"]
image:https://img.shields.io/mastodon/follow/109258009343975439?domain=https%3A%2F%2Fmastodon.social&style=social[Mastodon Follow]

Sets up Oracle Database using Container images from link:https://container-registry.oracle.com[] or link:https://github.com/gvenzl/oci-oracle-xe[gvenzl/oci-oracle-xe].

IMPORTANT: Only *Linux* runners are supported for the time being.

== Inputs

Following inputs may be used as `step.with` keys when using images from `container-registry.oracle.com`:

[%header,cols="<2,<,<,<3",width="100%"]
|===
| Name               | Required | Default                      | Description
| image              | true     |                              | Full image name and tag such as `container-registry.oracle.com/database/enterprise:21.3.0.0`
| registry           |          |                              | Registry where the image may be found, i.e, `container-registry.oracle.com`
| registry-username  |          |                              | If specified, the action will log into the registry with that user
| registry-password  |          |                              | If specified, the action will log into the registry with that password
| port               |          | 1521                         | Exposed port for database connections
| volume             |          |                              | Volume to be mounted to contain database files
| setup-scripts      |          |                              | Path to folder with additional database setup scripts
| startup-scripts    |          |                              | Path to folder with additional database startup scripts
| container-name     |          | oracledb                     | Name for the database container
| health-script-path |          | /opt/oracle/checkDBStatus.sh | Path to heclthcheck script found inside the image
| health-max-retries |          | 20                           | Number of tries for checking that the database is up
| health-interval    |          | 10                           | Time interval between health checks, in seconds
|===

Following environment variables will be passed to the container when using images from `container-registry.oracle.com`:

[%header,cols="<,<3",width="100%"]
|===
| Name                | Description
| ORACLE_SID          | The Oracle Database SID that should be used (default: ORCLCDB)
| ORACLE_PDB          | The Oracle Database PDB name that should be used (default: ORCLPDB1)
| ORACLE_PWD          | The Oracle Database SYS, SYSTEM and PDBADMIN password (default: auto generated)
| INIT_SGA_SIZE       | The total memory in MB that should be used for all SGA components (optional)
| INIT_PGA_SIZE       | The target aggregate PGA memory in MB that should be used for all server processes attached to the instance (optional)
| ORACLE_EDITION      | The Oracle Database Edition (enterprise/standard, default: enterprise)
| ORACLE_CHARACTERSET | The character set to use when creating the database (default: AL32UTF8)
| ENABLE_ARCHIVELOG   | To enable archive log mode when creating the database (default: false). Supported from 19.3 onwards.
|===

Following inputs may be used as `step.with` keys when using images from `gvenzl/oracle-xe` :

[%header,cols="<2,<,<,<3",width="100%"]
|===
| Name               | Required | Default  | Description
| tag                |          | latest   | Valid image tag from link:https://github.com/gvenzl/oci-oracle-xe[gvenzl/oci-oracle-xe]
| port               |          | 1521     | Exposed port for database connections
| volume             |          |          | Volume to be mounted to contain database files
| oracle-password    |          |          | Password for the Oracle Database `SYS` and `SYSTEM` users
| oracle-database    |          |          | Create a new pluggable database with the specified name
| app-user           | true     |          | Create a new database schema user with the specified name
| app-user-password  | true     |          | Define a password for the database schema user specified by `app-user`
| setup-scripts      |          |          | Path to folder with additional database setup scripts
| startup-scripts    |          |          | Path to folder with additional database startup scripts
| container-name     |          | oracledb | Name for the database container
| health-max-retries |          | 20       | Number of tries for checking that the database is up
| health-interval    |          | 10       | Time interval between health checks, in seconds
|===

A random password will be generated automatically if a value for `oracle-password` is not supplied.

== Usage

=== Oracle Database from `container-registry.oracle.com`

Log into `container-registry.oracle.com` and run Oracle Enteprise Edition 21.3.0.0

[source,yaml]
[subs="attributes"]
----
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: {project-owner}/{project-name}@{project-tag}
        with:
          image: container-registry.oracle.com/database/enterprise:21.3.0.0
          registry: container-registry.oracle.com
          registry-username: ${{ secrets.OCR_USERNAME }}
          registry-password: ${{ secrets.OCR_PASSWORD }}
        env:
          ORACLE_PWD: ${{ secrets.ORACLE_PASSWORD }}
----

Alternatively you may log into the container registry using an external action:

[source,yaml]
[subs="attributes"]
----
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: container-registry.oracle.com
          username: ${{ secrets.OCR_USERNAME }}
          password: ${{ secrets.OCR_PASSWORD }}
      - uses: {project-owner}/{project-name}@{project-tag}
        with:
          image: container-registry.oracle.com/database/enterprise:21.3.0.0
        env:
          ORACLE_PWD: ${{ secrets.ORACLE_PASSWORD }}
----

=== Basic usage with Oracle Database Express Edition from `gvenzl/oracle-xe`

All defaults enabled as explained link:https://github.com/gvenzl/oci-oracle-xe#github-actions[here].

[source,yaml]
[subs="attributes"]
----
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: {project-owner}/{project-name}@{project-tag}
        with:
          app-user: &lt;username&gt;
          app-user-password: &lt;password&gt;
----

NOTE: You must define values of `app-user` and `app-user-password`, either explicitly, via env vars, or secrets.

=== Custom Database Password

Set a custom database password that you may use at a later step to perform admin operations.

[source,yaml]
[subs="attributes"]
----
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: {project-owner}/{project-name}@{project-tag}
        with:
          app-user: &lt;username&gt;
          app-user-password: &lt;password&gt;
          oracle-password: ${{ secrets.ORACLE_PASSWORD }}
----

NOTE: Use a secret or explicitly mask the password before using it.

=== Persistent Database Container

Database files placed at `~/database-files` inside the GitHub Action runner will be read and used. You may choose a different location according to your needs.

[source,yaml]
[subs="attributes"]
----
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir ${{ github.workspace }}/database-files
      - uses: {project-owner}/{project-name}@{project-tag}
        with:
          app-user: &lt;username&gt;
          app-user-password: &lt;password&gt;
          volume: ${{ github.workspace }}/database-files
----

NOTE: The directory `~/database-files` must be writtable by the `oracle` (uid: 54321) user.

=== Init scripts

SQL scripts placed at `~/my-scripts` inside the GitHub Action runner will be used to post initialize the database.

[source,yaml]
[subs="attributes"]
----
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: {project-owner}/{project-name}@{project-tag}
        with:
          app-user: &lt;username&gt;
          app-user-password: &lt;password&gt;
          startup-scripts: ${{ github.workspace }}/my-scripts
----

== Why

The documentation from link:https://github.com/gvenzl/oci-oracle-xe[gvenzl/oci-oracle-xe] shows that GitHub services may
be used with the images. An example is shown next:

[source, yaml]
----
    services:
      # Oracle service (label used to access the service container)
      oracle:
        # Docker Hub image (feel free to change the tag "latest" to any other available one)
        image: gvenzl/oracle-xe:latest

        # Provide passwords and other environment variables to container
        env:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: my_user
          APP_USER_PASSWORD: my_password_which_I_really_should_change

        # Forward Oracle port
        ports:
          - 1521:1521

        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
----

This action builds on top of the capabilities offered by `gvenzl/oci-oracle-xe` adding the following options:

 - managed docker image name & tag
 - managed database port
 - automatic mapping of database volume path (11gR2 uses `/u01/app/oracle/oradata/XE`, all other versions use `/opt/oracle/oradata`)
 - automatic mapping of external database initialization scripts
 - automatic health checks upon starting the container

Thus, switching from container service to action results in the following configuration:

[source,yaml]
[subs="attributes"]
----
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: {project-owner}/{project-name}@{project-tag}
        with:
          app-user: my_user
          app-user-password: my_password_which_I_really_should_change
----

Updating this configuration to persist the database volume between runs:

[source,yaml]
[subs="attributes"]
----
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir ${{ github.workspace }}/database-files
      - uses: {project-owner}/{project-name}@{project-tag}
        with:
          app-user: my_user
          app-user-password: my_password_which_I_really_should_change
          volume: ${{ github.workspace }}/database-files
----
